In [38]:
import pandas as pd

In [39]:
data = pd.read_excel('score.xlsx',engine='openpyxl',sheet_name='Sheet2')

In [40]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        13 non-null     str
 1   Strength    13 non-null     str
 2   Strength.1  13 non-null     str
 3   Strength.2  13 non-null     str
 4   Strength.3  11 non-null     str
 5   Strength.4  10 non-null     str
 6   Weakness    13 non-null     str
 7   Weakness.1  13 non-null     str
 8   Weakness.2  13 non-null     str
 9   Weakness.3  9 non-null      str
 10  Weakness.4  8 non-null      str
dtypes: str(11)
memory usage: 1.2 KB

In [41]:
strength_cols = [c for c in data.columns if "strength" in c.lower()]
weakness_cols = [c for c in data.columns if "weakness" in c.lower()]

In [42]:
strength_cols, weakness_cols

(['Strength', 'Strength.1', 'Strength.2', 'Strength.3', 'Strength.4'],
 ['Weakness', 'Weakness.1', 'Weakness.2', 'Weakness.3', 'Weakness.4'])

In [43]:
strengths = data.melt(
    id_vars=["Name"],
    value_vars=strength_cols,
    value_name="category"
)
strengths["Type"] = "Strength"

In [44]:
weaknesses = data.melt(
    id_vars=["Name"],
    value_vars=weakness_cols,
    value_name="category"
)
weaknesses["Type"] = "Weakness"

In [45]:
result = pd.concat([strengths, weaknesses], ignore_index=True)

In [46]:
result.info()

<class 'pandas.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      130 non-null    str
 1   variable  130 non-null    str
 2   category  116 non-null    str
 3   Type      130 non-null    str
dtypes: str(4)
memory usage: 4.2 KB

In [47]:
result.to_csv('result.csv', index=False)

In [48]:
result

              Name    variable        category      Type
0              Muz    Strength       Geography  Strength
1    Adwait Sohoni    Strength      Technology  Strength
2          Rishabh    Strength         History  Strength
3           Vishal    Strength           Maths  Strength
4      BadhirPanda    Strength         History  Strength
..             ...         ...             ...       ...
125          Goose  Weakness.4    Social Media  Weakness
126        Soumeet  Weakness.4  Literature/Art  Weakness
127      Saksshiii  Weakness.4             NaN  Weakness
128           Isha  Weakness.4         Biology  Weakness
129          Kanak  Weakness.4             NaN  Weakness

[130 rows x 4 columns]

In [49]:
result[["Name", "Type"]].groupby("Type").count().reset_index().sort_values("Name", ascending=False)

       Type  Name
0  Strength    65
1  Weakness    65